### ISSUE TITLE
Getting Temporary failure in name resolution error while using this model. 

### ISSUE THREAD

**Issue by devanghingu** [MaartenGr/KeyBERT#131]
i using this package(keybert==0.5.0) for test purpose but i get following error 
```
Traceback (most recent call last):
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/gevent/_socketcommon.py", line 247, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/gevent/resolver/thread.py", line 63, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/gevent/pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 359, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 347, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/gevent/threadpool.py", line 167, in __run_task
    thread_result.set(func(*args, **kwargs))
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9df4bead30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9df4bead30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/ml_env/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/bin/celery.py", line 495, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/bin/celery.py", line 487, in handle_argv
    return self.execute(command, argv)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/bin/celery.py", line 415, in execute
    return cls(
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/bin/base.py", line 253, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/bin/worker.py", line 253, in run
    worker = self.app.Worker(
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/worker/worker.py", line 99, in __init__
    self.app.loader.init_worker()
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/loaders/base.py", line 109, in import_default_modules
    return [self.import_task_module(m) for m in self.default_modules]
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/loaders/base.py", line 109, in <listcomp>
    return [self.import_task_module(m) for m in self.default_modules]
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/loaders/base.py", line 89, in import_task_module
    return self.import_from_cwd(module)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/loaders/base.py", line 95, in import_from_cwd
    return import_from_cwd(
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/celery/loaders/base.py", line 92, in import_module
    return importlib.import_module(module, package=package)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/invenio-ml-backend/tasks/__init__.py", line 1, in <module>
    from tasks.ml_tasks import mlengine
  File "/home/ubuntu/invenio-ml-backend/tasks/ml_tasks.py", line 4, in <module>
    from services.inference import request_task#, Inference
  File "/home/ubuntu/invenio-ml-backend/services/__init__.py", line 31, in <module>
    key_bert_model = KeyBERT()
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/keybert/_model.py", line 49, in __init__
    self.model = select_backend(model)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/keybert/backend/_utils.py", line 43, in select_backend
    return SentenceTransformerBackend(embedding_model)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/keybert/backend/_sentencetransformers.py", line 35, in __init__
    self.embedding_model = SentenceTransformer(embedding_model)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 80, in __init__
    snapshot_download(model_name_or_path,
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/sentence_transformers/util.py", line 426, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 247, in model_info
    r = requests.get(path, headers=headers)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/ml_env/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9df4bead30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by MaartenGr** [comment]
Based on your error, it seems you are having difficulties connecting to the internet. Perhaps you are offline, make sure you are online and have a stable connection since the model needs to be downloaded before it can be used.

**Comment by devanghingu** [comment]
Actually i testing it with AWS  instance. 
@MaartenGr

**Comment by MaartenGr** [comment]
It might still be the case that connecting to the internet from within your instance might be difficult. Are you using a local model or the default settings in KeyBERT? If it is the latter, then it does seem that your instance has trouble connecting with the huggingface servers.

**Comment by devanghingu** [comment]
Hey @MaartenGr. currently i m not getting this error, everything working fine. i guess there might be issues network at that time.

thanks @MaartenGr for quick response :clap:
