### ISSUE TITLE
Problem with scipy during install: Preparing wheel metadata ... error, ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by patmull** [MaartenGr/KeyBERT#29]
Weird problem happens to me when I'm trying to install _keyBERT_ on my laptop. It fails during a scipy dependency check. On my desktop it's working, even with the same project and other packages. For some reason it doesn't work for me even at blank empty project without any other packages.

I'm using Pycharm with virtual interpreter, Python 3.8, pip 21.0.1, setuptools 56.0.0. 

I would really appreciate any help.

This is the exact output, I only slightly censored my folder strucuture.

`C:\my-path>pip install keybert
Collecting keybert
  Using cached keybert-0.2.0.tar.gz (12 kB)
Collecting sentence-transformers>=0.3.8
  Using cached sentence-transformers-1.0.4.tar.gz (74 kB)
Requirement already satisfied: scikit-learn>=0.22.2 in c:\my-path\appdata\local\programs\python\python38-32\lib\site-packages (from keybert) (0
.24.1)
Requirement already satisfied: numpy>=1.18.5 in c:\my-path\appdata\local\programs\python\python38-32\lib\site-packages (from keybert) (1.19.5)
Requirement already satisfied: joblib>=0.11 in c:\my-path\appdata\local\programs\python\python38-32\lib\site-packages (from scikit-learn>=0.22.
2->keybert) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\my-path\appdata\local\programs\python\python38-32\lib\site-packages (from scikit-lear
n>=0.22.2->keybert) (2.1.0)
Requirement already satisfied: scipy>=0.19.1 in c:\my-path\appdata\local\programs\python\python38-32\lib\site-packages (from scikit-learn>=0.22
.2->keybert) (1.6.2)
Collecting transformers<5.0.0,>=3.1.0
  Using cached transformers-4.5.1-py3-none-any.whl (2.1 MB)
Requirement already satisfied: tqdm in c:\my-path\appdata\local\programs\python\python38-32\lib\site-packages (from sentence-transformers>=0.3.
8->keybert) (4.54.1)
Collecting sentence-transformers>=0.3.8
  Using cached sentence-transformers-1.0.3.tar.gz (74 kB)
  Using cached sentence-transformers-1.0.2.tar.gz (74 kB)
  Using cached sentence-transformers-1.0.1.tar.gz (74 kB)
  Using cached sentence-transformers-1.0.0.tar.gz (74 kB)
  Using cached sentence-transformers-0.4.1.2.tar.gz (64 kB)
  Using cached sentence-transformers-0.4.1.1.tar.gz (64 kB)
  Using cached sentence-transformers-0.4.1.tar.gz (64 kB)
  Using cached sentence-transformers-0.4.0.tar.gz (65 kB)
  Using cached sentence-transformers-0.3.9.tar.gz (64 kB)
Collecting transformers<3.6.0,>=3.1.0
  Using cached transformers-3.5.1-py3-none-any.whl (1.3 MB)
Collecting sentence-transformers>=0.3.8
  Using cached sentence-transformers-0.3.8.tar.gz (66 kB)
Collecting transformers<3.4.0,>=3.1.0
  Using cached transformers-3.3.1-py3-none-any.whl (1.1 MB)
INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
Collecting scipy>=0.19.1
  Using cached scipy-1.6.1-cp38-cp38-win32.whl (29.5 MB)
  Using cached scipy-1.6.0-cp38-cp38-win32.whl (29.5 MB)
  Using cached scipy-1.5.4-cp38-cp38-win32.whl (28.4 MB)
  Using cached scipy-1.5.3-cp38-cp38-win32.whl (28.4 MB)
  Using cached scipy-1.5.2-cp38-cp38-win32.whl (28.4 MB)
  Using cached scipy-1.5.1-cp38-cp38-win32.whl (28.4 MB)
  Using cached scipy-1.5.0-cp38-cp38-win32.whl (28.4 MB)
  Using cached scipy-1.4.1-cp38-cp38-win32.whl (27.9 MB)
  Using cached scipy-1.4.0-cp38-cp38-win32.whl (27.9 MB)
  Using cached scipy-1.3.3-cp38-cp38-win32.whl (27.4 MB)
  Using cached scipy-1.3.2-cp38-cp38-win32.whl (27.4 MB)
  Using cached scipy-1.3.1.tar.gz (23.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\my-path\appdata\local\programs\python\python38-32\python.exe' 'c:\my-path\appdata\local\programs\python\python38-32\lib\s
ite-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\my-path\AppData\Local\Temp\tmpquyu57o9'
         cwd: C:\my-path\AppData\Local\Temp\pip-install-3scfomzx\scipy_98374e591d234ac8937f2333572e7063
    Complete output (192 lines):
    lapack_opt_info:
    lapack_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['c:\\users\\patri\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\patri\\appdata\\lo
cal\\programs\\python\\python38-32\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas not found in ['c:\\users\\patri\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\patri\\appdata\\
local\\programs\\python\\python38-32\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    openblas_clapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries openblas,lapack not found in ['c:\\users\\patri\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\patri\\ap
pdata\\local\\programs\\python\\python38-32\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\my-path\appdata\local\programs\python\python38-32\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\my-path\appdata\local\programs\python\python38-32\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries tatlas,tatlas not found in c:\my-path\appdata\local\programs\python\python38-32\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\my-path\appdata\local\programs\python\python38-32\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\my-path\appdata\local\programs\python\python38-32\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\my-path\appdata\local\programs\python\python38-32\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries satlas,satlas not found in c:\my-path\appdata\local\programs\python\python38-32\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\my-path\appdata\local\programs\python\python38-32\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\my-path\appdata\local\programs\python\python38-32\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\my-path\appdata\local\programs\python\python38-32\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries ptf77blas,ptcblas,atlas not found in c:\my-path\appdata\local\programs\python\python38-32\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\my-path\appdata\local\programs\python\python38-32\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\my-path\appdata\local\programs\python\python38-32\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\my-path\appdata\local\programs\python\python38-32\lib
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in C:\
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries f77blas,cblas,atlas not found in c:\my-path\appdata\local\programs\python\python38-32\libs
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack_atlas not found in c:\my-path\appdata\local\programs\python\python38-32\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries lapack not found in ['c:\\users\\patri\\appdata\\local\\programs\\python\\python38-32\\lib', 'C:\\', 'c:\\users\\patri\\appdata\\lo
cal\\programs\\python\\python38-32\\libs']
      NOT AVAILABLE

    lapack_src_info:
      NOT AVAILABLE

      NOT AVAILABLE

    setup.py:386: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\my-path\AppData\Local\Temp\pip-modern-metadata-5c5bml6
g'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from scipy source directory.
    C:\my-path\AppData\Local\Temp\pip-build-env-0dcoq7t6\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    C:\my-path\AppData\Local\Temp\pip-build-env-0dcoq7t6\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    C:\my-path\AppData\Local\Temp\pip-build-env-0dcoq7t6\overlay\Lib\site-packages\numpy\distutils\system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    Traceback (most recent call last):
      File "c:\my-path\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "c:\my-path\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\my-path\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_met
adata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\my-path\AppData\Local\Temp\pip-build-env-0dcoq7t6\overlay\Lib\site-packages\setuptools\build_meta.py", line 166, in prepare_meta
data_for_build_wheel
        self.run_setup()
      File "C:\my-path\AppData\Local\Temp\pip-build-env-0dcoq7t6\overlay\Lib\site-packages\setuptools\build_meta.py", line 258, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\my-path\AppData\Local\Temp\pip-build-env-0dcoq7t6\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 505, in <module>
        setup_package()
      File "setup.py", line 501, in setup_package
        setup(**metadata)
      File "C:\my-path\AppData\Local\Temp\pip-build-env-0dcoq7t6\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "setup.py", line 403, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz#s
ha256=2643cfb46d97b7797d1dbdb6f3c23fe3402904e3c90e6facfe6a9b98d808c1b5 (from https://pypi.org/simple/scipy/) (requires-python:>=3.5). Command error
ed out with exit status 1: 'c:\my-path\appdata\local\programs\python\python38-32\python.exe' 'c:\my-path\appdata\local\programs\python\pyth
on38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\my-path\AppData\Local\Temp\tmpquyu57o9' Check
 the logs for full command output`

**Comment by MaartenGr** [comment]
From a quick look, I could not tell you what the issue here is. Scipy is installed through one of the following packages:
* "sentence-transformers>=0.3.8"
* "scikit-learn>=0.22.2"
* "numpy>=1.18.5"

Which are essentially all base dependencies found in `setup.py`. I would suggest starting from a fresh (ana)conda environment seeing as I see many "Requirement already satisfied" messages. I am curious to see if it still gives an error if there are no other packages already installed.

**Comment by AbhiPawar5** [comment]
Hi @MaartenGr , I am facing one of the similar issues. My environment is:
keybert==0.2.0
numpy==1.19.5
pandas==1.1.5
scikit-learn==0.22.2

and when I try importing keyBERT it says,
ImportError: dlopen: cannot load any more object with static TLS

**Comment by MaartenGr** [comment]
@AbhiPawar5 Based on the packages you have installed I would advise you to start from a fresh environment and install the latest version of KeyBERT. Seems you are using an earlier version which has some issues with numpy/scipy/pypi.

**Comment by AbhiPawar5** [comment]
Hi @MaartenGr , thanks for your input. I did try it my fresh environment which solved earlier issue but encountered a new one:
certifi==2020.12.5
chardet==4.0.0
click==8.0.1
dataclasses==0.8
decorator==4.4.2
filelock==3.0.12
huggingface-hub==0.0.8
idna==2.10
importlib-metadata==4.0.1
jellyfish==0.8.2
joblib==1.0.1
keybert==0.3.0
networkx==2.5.1
nltk==3.6.2
numpy==1.19.5
packaging==20.9
pandas==1.1.5
Pillow==8.2.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
regex==2021.4.4
requests==2.25.1
sacremoses==0.0.45
scikit-learn==0.23.2
scipy==1.5.4
segtok==1.5.10
sentence-transformers==1.2.0
sentencepiece==0.1.95
six==1.16.0
tabulate==0.8.9
threadpoolctl==2.1.0
tokenizers==0.10.3
torch==1.8.1
torchvision==0.9.1
tqdm==4.61.0
transformers==4.6.1
typing-extensions==3.10.0.0
urllib3==1.26.4
yake==0.4.8
zipp==3.4.1

But still seems to have some other issue:
```
$ python --version
Python 3.6.8
```

```
$ python
Python 3.6.8 (default, Dec 25 2018, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from keybert import KeyBERT
>>> distilbert_model = KeyBERT('distilbert-base-nli-mean-tokens')
Segmentation fault (core dumped)
```

**Comment by MaartenGr** [comment]
Strange, that seems to be a C++ error. From what I could gather, perhaps a wrong install of Python could be the culprit here (see [this](https://stackoverflow.com/questions/13654449/error-segmentation-fault-core-dumped)). I did several tests and could not reproduce this issue so I am afraid I cannot be of much help. 

The only thing that I can think of is that you have too little memory available to actually download and prepare the model.
