### ISSUE TITLE
KeyError: '__version__' Problem

### ISSUE THREAD

**Issue by shaoniana1997** [MaartenGr/KeyBERT#95]
Hello,Thanks for your nice Job! I am trying to reproduce your project,but i came across a problem ,here is the detail:
①.pip install keybert -> ②.from keybert import KeyBERT ->③.kw_model = KeyBERT()
I came a across in ③：
100%|█████████████████████████████████████████████████████████████████████████████████| 83.5M/83.5M [18:06<00:00, 76.8kB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lixin/enter/envs/PR-VIST/lib/python3.7/site-packages/keybert/_model.py", line 49, in __init__
    self.model = select_backend(model)
  File "/home/lixin/enter/envs/PR-VIST/lib/python3.7/site-packages/keybert/backend/_utils.py", line 43, in select_backend
    return SentenceTransformerBackend(embedding_model)
  File "/home/lixin/enter/envs/PR-VIST/lib/python3.7/site-packages/keybert/backend/_sentencetransformers.py", line 35, in __init__
    self.embedding_model = SentenceTransformer(embedding_model)
  File "/home/lixin/enter/envs/PR-VIST/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 112, in __init__
    if config['__version__'] > __version__:
KeyError: '__version__'

can you give me some useful advice, thank you very much!!!!! @MaartenGr

**Comment by MaartenGr** [comment]
Apologies for the late response. I would advise starting from a fresh environment and installing KeyBERT there. Typically, issues with `version` key errors result from installations issues.

**Comment by shaoniana1997** [comment]
Thank you for your nice answer. i also have a question about the another project Concept , do you have free time to give me some advice?
URL: https://github.com/MaartenGr/Concept/issues/7#issue-1165995002
Thank you !

**Comment by MaartenGr** [comment]
No problem, glad I could help. Of course! Just answered the issue.
